name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint shell script
        run: |
          shellcheck deploy.sh
      - name: Echo success
        run: echo "CI pipeline completed successfully!"